openapi: 3.0.0
info:
  version: 1.0.0
  title: 📒 Account
  description: Paths and components
  contact:
    email: parkerkrhoyt@gmail.com  
  license:
    name: MIT
externalDocs:
  description: Find out more about Avocado
  url: http://kevinhoyt.com
servers:
- url: http://localhost:3000/api
tags:
- name: 📒 Account
  description: Account ownership of data sets
paths:
  /account:
    get:
      tags:
      - 📒 Account
      summary: Read all available accounts
      operationId: getAccounts
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    owner:
                      type: string
                      format: uuid
                    email:
                      type: string
                      example: thedude@biglebowski.com
                    role:
                      type: string
                      example: owner
                    token:
                      type: string
                      format: uuid
    post:
      tags:
      - 📒 Account
      summary: Create a new account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: string
                  format: uuid
                email:
                  type: string
                  example: thedude@biglebowski.com
                password:
                  type: string
                  format: password
                role:
                  type: string
                  example: owner
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  owner:
                    type: string
                    format: uuid
                  email:
                    type: string
                    example: thedude@biglebowski.com
                  role:
                    type: string
                    example: owner
                  token:
                    type: string
                    format: uuid
  /account/{id}:        
    parameters:
    - name: id
      in: path
      description: ID of a specific account
      required: true
      schema:
        type: string
        format: uuid      
    get:
      tags:
      - 📒 Account
      summary: Read specific account by ID
      operationId: getAccountByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  owner:
                    type: string
                    format: uuid
                  email:
                    type: string
                    example: thedude@biglebowski.com
                  role:
                    type: string
                    example: owner
                  token:
                    type: string
                    format: uuid                
    put:
      tags:
      - 📒 Account
      summary: Update specific account by ID
      operationId: updateAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: thedude@biglebowski.com
                owner:
                  type: string
                  format: uuid
                role:
                  type: string
                  example: owner
                password:
                  type: string
                  format: password
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  owner:
                    type: string
                    format: uuid
                  email:
                    type: string
                    example: thedude@biglebowski.com
                  role:
                    type: string
                    example: owner
                  token:
                    type: string
                    format: uuid             
    delete:
      tags:
      - 📒 Account
      summary: Delete specific account by ID
      operationId: deleteAccountByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid  
  /account/email:
    post: 
      tags:
      - 📒 Account
      summary: Check if account exists
      operationId: accountExists
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: thedude@biglebowski.com
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: thedude@biglebowski.com
                  found:
                    type: boolean
  /account/login:
    post: 
      tags:
      - 📒 Account
      summary: Login a specific account
      operationId: accountLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: thedude@biglebowski.com
                password:
                  type: string
                  format: password
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  owner:
                    type: string
                    format: uuid
                  email:
                    type: string
                    example: thedude@biglebowski.com
                  role:
                    type: string
                    example: view
                  token:
                    type: string
                    format: uuid 
  /account/{id}/token/refresh:
    parameters:
    - name: id
      in: path
      description: ID of a specific account
      required: true
      schema:
        type: string
        format: uuid   
    get: 
      tags:
      - 📒 Account
      summary: Refresh the token for a given account
      operationId: accountRefreshToken
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: uuid
  /account/email/{email}:
    parameters:
    - name: email
      in: path
      description: Email of a specific account
      required: true
      schema:
        type: string
        format: thedude@biglebowski.com   
    get: 
      tags:
      - 📒 Account
      summary: Read specific account by ID
      operationId: getAccountByEmail
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  owner:
                    type: string
                    format: uuid
                  email:
                    type: string
                    example: thedude@biglebowski.com
                  role:
                    type: string
                    example: view
                  token:
                    type: string
                    format: uuid
  /account/token/{token}:
    parameters:
    - name: token
      in: path
      description: Token of a specific account
      required: true
      schema:
        type: string
        format: uuid
    get: 
      tags:
      - 📒 Account
      summary: Read specific account by token
      operationId: getAccountByToken
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  owner:
                    type: string
                    format: uuid
                  email:
                    type: string
                    example: thedude@biglebowski.com
                  role:
                    type: string
                    example: view
                  token:
                    type: string
                    format: uuid                    
components:
  schemas:
    Account:
      required:
      - email
      type: object
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        owner:
          type: string
          format: uuid
        email:
          type: string
          example: thedude@biglebowski.com
        password:
          type: string
          format: password
        role:
          type: string
          example: view
        token:
          type: string
          format: uuid
