openapi: 3.0.0
info:
  version: 1.0.0
  title: 🖇️ Relationship
  description: Paths and components
  contact:
    email: parkerkrhoyt@gmail.com
  license:
    name: MIT
externalDocs:
  description: Find out more about Avocado
  url: http://kevinhoyt.com
servers:
- url: http://localhost:3000/api
security:
- ApiKeyAuth: []
tags:
- name: 🖇️ Relationship
  description: Business connections between stakeholders
paths:
  /relationship:
    get:
      tags:
      - 🖇️ Relationship
      summary: Read all available relationships
      operationId: getRelationships
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    account_id:
                      type: string
                      format: uuid
                    name:
                      type: string
                      example: ISV
                    color_id:
                      type: string
                      format: uuid
                    count:
                      type: integer
                      example: 0
    post:
      tags:
      - 🖇️ Relationship
      summary: Create a new relationship
      operationId: createRelationship
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: ISV
                color_id:
                  type: string
                  format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationship'
  /relationship/{id}:
    parameters:
    - name: id
      in: path
      description: ID field for desired relationship
      required: true
      schema:
        type: string
        format: uuid
    get:
      tags:
      - 🖇️ Relationship
      summary: Read specific relationship by ID
      operationId: getRelationshipByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationship'
    put:
      tags:
      - 🖇️ Relationship
      summary: Update specific relationship by ID
      operationId: updateRelationship
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: ISV
                color_id:
                  type: string
                  format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationship'
    delete:
      tags:
      - 🖇️ Relationship
      summary: Delete specific relationship by ID
      operationId: deleteRelationshipByID
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
  /relationship/name/{prefix}:
    parameters:
    - name: prefix
      in: path
      description: Prefix for a given relationship
      required: true
      schema:
        type: string
        example: IS
    get:
      tags:
      - 🖇️ Relationship
      summary: Search for relationship with given value
      operationId: searchRelationshipByName
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    account_id:
                      type: string
                      format: uuid
                    name:
                      type: string
                      example: ISV
                    color_id:
                      type: string
                      format: uuid
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Avocado
  schemas:
    Relationship:
      required:
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        account_id:
          type: string
          format: uuid
        name:
          type: string
          example: IBM
        color_id:
          type: string
          format: uuid
